name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{f21846f2-e664-41fb-81e4-32b2f2d43b47}}
          heroku_app_name: "fuady-bot"
          heroku_email: "fuadynur7@gmail.com"
          procfile: "web: npm start"
